# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

volumes:
  mongo_data:
  portainer_data:
  
services:
  basketdb:
    image: redis
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  catalogapi:
    image: catalogapi
    container_name: catalogapi
    environment:
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings:DatabaseName=CatalogDb
      - environmentVariables:ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    ports:
      - 5000:5000
    
  basketapi:
    image: basketapi
    container_name: basketapi
    environment:
      - CacheSettings:ConnectionString=basketdb:6379
      - environmentVariables:ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - basketdb
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
    ports:
      - 5001:5001